### PR TITLE
Assignment one

### PR DESCRIPTION
**Pull request by amitsindhwani**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Created a logical model listing one to many relationship between customer and customer purchases table.
Worked on multiple queries to pull out data from farmersmarket database, includes selecting, joining 2 or more tables, creating a temp table, retrieve aggregated data, conditions on aggregated data, sorting the data while displaying and using string modifiers for the dates etc. 

## What did you learn from the changes you have made?
How to use joins - inner, left outer join, how to create temp tables, how to extract aggregated data, sort the data

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
yes it easy to pull out the data that only shows id, but joining the tables and showing the master data like product names, customer names etc., shows more readable data.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
some syntax related issues! running temp table and insert queries in one go giving issues as the temp table doesn't exists. So had to runt he queries separately. 
In one case forgot to use left join and realize while testing the data that it's not giving all the records.

## How were these changes tested?
tested the results on DB browser and validated the data in the specific tables. 

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by efantinatti — APPROVED** [review]
Dear Amit Kumar Sindhwani

Session 1:
1 - Missing the relationship type.

Session 2:
2 - OK.

Session 3:
3 - Complete with warnings. Missing dates and groupying by dates on DATE - Q2.

Final:
4 - All remaining are good and you can merge your feature branch 'assignment-one' to 'main'.

Mark: 27 points.

**Comment by amitsindhwani** [comment]
Dear Ernani

Thanks for your time reviewing my PR, I have a few queries

Session 1:
1 - Missing the relationship type.
[Amit] - Are you talking about the logical model? I pushed that to the images folder and committed the chances, Kindly confirm if this is what you are looking for.

Session 2:
2 - OK.

Session 3:
3 - Complete with warnings. Missing dates and grouping by dates on DATE - Q2.
[Amit] - I purposely removed (although it said to use it as the previous query) from the query as it was showing the same month and year for all the records in the result set. 

Final:
4 - All remaining are good and you can merge your feature branch 'assignment-one' to 'main'.
[Amit] - Please confirm if I am missing anything else before I merge the PR.

Mark: 27 points.

**Comment by efantinatti** [comment]
Hi Amit Kumar Sindhwani

Session 1:
1 - The Session one looks ok. The PNG came with alpha zero (transparency) and for dark background it doesn't appear well. Adjusted your mark on it. + 2 pts.

Session 3:
2 - It works but partially complete as required by the question.

**Comment by amitsindhwani** [comment]
Dear Ernani
Apologies for the delay!
I have upated the query for section 3 to include the columns for month and year. Kindly take look
Thanks for your inputs!

Regards
Amit

**Comment by efantinatti** [comment]
All good. Thanks @amitsindhwani

**Comment by efantinatti** [comment]
You can merge it to `main`branch.

**Comment by amitsindhwani** [comment]
Merged into the main branch! Thanks Ernani

**Pull request merged**
